// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Registration.Persistence;

#nullable disable

namespace Registration.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260611155045_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Registration.Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FlatNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("GovernorateId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("Registration.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GovernorateId");

                    b.HasIndex("GovernorateId", "Name")
                        .IsUnique();

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            GovernorateId = 1,
                            IsActive = true,
                            Name = "Nasr City"
                        },
                        new
                        {
                            Id = 102,
                            GovernorateId = 1,
                            IsActive = true,
                            Name = "Maadi"
                        },
                        new
                        {
                            Id = 103,
                            GovernorateId = 1,
                            IsActive = true,
                            Name = "Heliopolis"
                        },
                        new
                        {
                            Id = 104,
                            GovernorateId = 1,
                            IsActive = true,
                            Name = "Downtown Cairo"
                        },
                        new
                        {
                            Id = 105,
                            GovernorateId = 1,
                            IsActive = true,
                            Name = "Helwan"
                        },
                        new
                        {
                            Id = 106,
                            GovernorateId = 1,
                            IsActive = true,
                            Name = "Shubra"
                        },
                        new
                        {
                            Id = 107,
                            GovernorateId = 1,
                            IsActive = true,
                            Name = "New Cairo"
                        },
                        new
                        {
                            Id = 108,
                            GovernorateId = 1,
                            IsActive = true,
                            Name = "Madinaty"
                        },
                        new
                        {
                            Id = 201,
                            GovernorateId = 2,
                            IsActive = true,
                            Name = "Dokki"
                        },
                        new
                        {
                            Id = 202,
                            GovernorateId = 2,
                            IsActive = true,
                            Name = "Mohandessin"
                        },
                        new
                        {
                            Id = 203,
                            GovernorateId = 2,
                            IsActive = true,
                            Name = "6th of October"
                        },
                        new
                        {
                            Id = 204,
                            GovernorateId = 2,
                            IsActive = true,
                            Name = "Haram"
                        },
                        new
                        {
                            Id = 205,
                            GovernorateId = 2,
                            IsActive = true,
                            Name = "Imbaba"
                        },
                        new
                        {
                            Id = 206,
                            GovernorateId = 2,
                            IsActive = true,
                            Name = "Faisal"
                        },
                        new
                        {
                            Id = 207,
                            GovernorateId = 2,
                            IsActive = true,
                            Name = "Sheikh Zayed"
                        },
                        new
                        {
                            Id = 208,
                            GovernorateId = 2,
                            IsActive = true,
                            Name = "Badrasheen"
                        },
                        new
                        {
                            Id = 301,
                            GovernorateId = 3,
                            IsActive = true,
                            Name = "Sidi Gaber"
                        },
                        new
                        {
                            Id = 302,
                            GovernorateId = 3,
                            IsActive = true,
                            Name = "Smouha"
                        },
                        new
                        {
                            Id = 303,
                            GovernorateId = 3,
                            IsActive = true,
                            Name = "Miami"
                        },
                        new
                        {
                            Id = 304,
                            GovernorateId = 3,
                            IsActive = true,
                            Name = "Montaza"
                        },
                        new
                        {
                            Id = 305,
                            GovernorateId = 3,
                            IsActive = true,
                            Name = "Borg El Arab"
                        },
                        new
                        {
                            Id = 306,
                            GovernorateId = 3,
                            IsActive = true,
                            Name = "Agami"
                        },
                        new
                        {
                            Id = 307,
                            GovernorateId = 3,
                            IsActive = true,
                            Name = "Sidi Bishr"
                        },
                        new
                        {
                            Id = 308,
                            GovernorateId = 3,
                            IsActive = true,
                            Name = "Mansheya"
                        },
                        new
                        {
                            Id = 401,
                            GovernorateId = 4,
                            IsActive = true,
                            Name = "Banha"
                        },
                        new
                        {
                            Id = 402,
                            GovernorateId = 4,
                            IsActive = true,
                            Name = "Shubra El-Kheima"
                        },
                        new
                        {
                            Id = 403,
                            GovernorateId = 4,
                            IsActive = true,
                            Name = "Qalyub"
                        },
                        new
                        {
                            Id = 404,
                            GovernorateId = 4,
                            IsActive = true,
                            Name = "Qaha"
                        },
                        new
                        {
                            Id = 405,
                            GovernorateId = 4,
                            IsActive = true,
                            Name = "Khanka"
                        },
                        new
                        {
                            Id = 406,
                            GovernorateId = 4,
                            IsActive = true,
                            Name = "Tukh"
                        },
                        new
                        {
                            Id = 407,
                            GovernorateId = 4,
                            IsActive = true,
                            Name = "Kafr Shukr"
                        },
                        new
                        {
                            Id = 408,
                            GovernorateId = 4,
                            IsActive = true,
                            Name = "Obour"
                        },
                        new
                        {
                            Id = 501,
                            GovernorateId = 5,
                            IsActive = true,
                            Name = "Zagazig"
                        },
                        new
                        {
                            Id = 502,
                            GovernorateId = 5,
                            IsActive = true,
                            Name = "10th of Ramadan City"
                        },
                        new
                        {
                            Id = 503,
                            GovernorateId = 5,
                            IsActive = true,
                            Name = "Belbeis"
                        },
                        new
                        {
                            Id = 504,
                            GovernorateId = 5,
                            IsActive = true,
                            Name = "Abu Hammad"
                        },
                        new
                        {
                            Id = 505,
                            GovernorateId = 5,
                            IsActive = true,
                            Name = "Faqous"
                        },
                        new
                        {
                            Id = 506,
                            GovernorateId = 5,
                            IsActive = true,
                            Name = "Minya Al Qamh"
                        },
                        new
                        {
                            Id = 507,
                            GovernorateId = 5,
                            IsActive = true,
                            Name = "Husseiniya"
                        },
                        new
                        {
                            Id = 508,
                            GovernorateId = 5,
                            IsActive = true,
                            Name = "Diyarb Negm"
                        },
                        new
                        {
                            Id = 601,
                            GovernorateId = 6,
                            IsActive = true,
                            Name = "Mansoura"
                        },
                        new
                        {
                            Id = 602,
                            GovernorateId = 6,
                            IsActive = true,
                            Name = "Talkha"
                        },
                        new
                        {
                            Id = 603,
                            GovernorateId = 6,
                            IsActive = true,
                            Name = "Mit Ghamr"
                        },
                        new
                        {
                            Id = 604,
                            GovernorateId = 6,
                            IsActive = true,
                            Name = "Dikirnis"
                        },
                        new
                        {
                            Id = 605,
                            GovernorateId = 6,
                            IsActive = true,
                            Name = "Aga"
                        },
                        new
                        {
                            Id = 606,
                            GovernorateId = 6,
                            IsActive = true,
                            Name = "Belqas"
                        },
                        new
                        {
                            Id = 607,
                            GovernorateId = 6,
                            IsActive = true,
                            Name = "Sherbin"
                        },
                        new
                        {
                            Id = 608,
                            GovernorateId = 6,
                            IsActive = true,
                            Name = "Mit Salsil"
                        },
                        new
                        {
                            Id = 701,
                            GovernorateId = 7,
                            IsActive = true,
                            Name = "Damanhur"
                        },
                        new
                        {
                            Id = 702,
                            GovernorateId = 7,
                            IsActive = true,
                            Name = "Kafr El Dawwar"
                        },
                        new
                        {
                            Id = 703,
                            GovernorateId = 7,
                            IsActive = true,
                            Name = "Rashid"
                        },
                        new
                        {
                            Id = 704,
                            GovernorateId = 7,
                            IsActive = true,
                            Name = "Edku"
                        },
                        new
                        {
                            Id = 705,
                            GovernorateId = 7,
                            IsActive = true,
                            Name = "Abu Hummus"
                        },
                        new
                        {
                            Id = 706,
                            GovernorateId = 7,
                            IsActive = true,
                            Name = "Itay El Baroud"
                        },
                        new
                        {
                            Id = 707,
                            GovernorateId = 7,
                            IsActive = true,
                            Name = "Hosh Issa"
                        },
                        new
                        {
                            Id = 708,
                            GovernorateId = 7,
                            IsActive = true,
                            Name = "Kom Hamada"
                        },
                        new
                        {
                            Id = 801,
                            GovernorateId = 8,
                            IsActive = true,
                            Name = "Minya"
                        },
                        new
                        {
                            Id = 802,
                            GovernorateId = 8,
                            IsActive = true,
                            Name = "Mallawi"
                        },
                        new
                        {
                            Id = 803,
                            GovernorateId = 8,
                            IsActive = true,
                            Name = "Beni Mazar"
                        },
                        new
                        {
                            Id = 804,
                            GovernorateId = 8,
                            IsActive = true,
                            Name = "Maghagha"
                        },
                        new
                        {
                            Id = 805,
                            GovernorateId = 8,
                            IsActive = true,
                            Name = "Samalut"
                        },
                        new
                        {
                            Id = 806,
                            GovernorateId = 8,
                            IsActive = true,
                            Name = "Matai"
                        },
                        new
                        {
                            Id = 807,
                            GovernorateId = 8,
                            IsActive = true,
                            Name = "Abu Qurqas"
                        },
                        new
                        {
                            Id = 808,
                            GovernorateId = 8,
                            IsActive = true,
                            Name = "Deir Mawas"
                        },
                        new
                        {
                            Id = 901,
                            GovernorateId = 9,
                            IsActive = true,
                            Name = "Qena"
                        },
                        new
                        {
                            Id = 902,
                            GovernorateId = 9,
                            IsActive = true,
                            Name = "Naqada"
                        },
                        new
                        {
                            Id = 903,
                            GovernorateId = 9,
                            IsActive = true,
                            Name = "Qus"
                        },
                        new
                        {
                            Id = 904,
                            GovernorateId = 9,
                            IsActive = true,
                            Name = "Nag Hammadi"
                        },
                        new
                        {
                            Id = 905,
                            GovernorateId = 9,
                            IsActive = true,
                            Name = "Dishna"
                        },
                        new
                        {
                            Id = 906,
                            GovernorateId = 9,
                            IsActive = true,
                            Name = "Abu Tesht"
                        },
                        new
                        {
                            Id = 907,
                            GovernorateId = 9,
                            IsActive = true,
                            Name = "Farshut"
                        },
                        new
                        {
                            Id = 908,
                            GovernorateId = 9,
                            IsActive = true,
                            Name = "Qift"
                        },
                        new
                        {
                            Id = 1001,
                            GovernorateId = 10,
                            IsActive = true,
                            Name = "Sohag"
                        },
                        new
                        {
                            Id = 1002,
                            GovernorateId = 10,
                            IsActive = true,
                            Name = "Akhmim"
                        },
                        new
                        {
                            Id = 1003,
                            GovernorateId = 10,
                            IsActive = true,
                            Name = "Girga"
                        },
                        new
                        {
                            Id = 1004,
                            GovernorateId = 10,
                            IsActive = true,
                            Name = "Tahta"
                        },
                        new
                        {
                            Id = 1005,
                            GovernorateId = 10,
                            IsActive = true,
                            Name = "Tama"
                        },
                        new
                        {
                            Id = 1006,
                            GovernorateId = 10,
                            IsActive = true,
                            Name = "Maragha"
                        },
                        new
                        {
                            Id = 1007,
                            GovernorateId = 10,
                            IsActive = true,
                            Name = "El Balyana"
                        },
                        new
                        {
                            Id = 1008,
                            GovernorateId = 10,
                            IsActive = true,
                            Name = "Dar El Salam"
                        },
                        new
                        {
                            Id = 1101,
                            GovernorateId = 11,
                            IsActive = true,
                            Name = "Assiut"
                        },
                        new
                        {
                            Id = 1102,
                            GovernorateId = 11,
                            IsActive = true,
                            Name = "Dairut"
                        },
                        new
                        {
                            Id = 1103,
                            GovernorateId = 11,
                            IsActive = true,
                            Name = "Manfalut"
                        },
                        new
                        {
                            Id = 1104,
                            GovernorateId = 11,
                            IsActive = true,
                            Name = "Abnub"
                        },
                        new
                        {
                            Id = 1105,
                            GovernorateId = 11,
                            IsActive = true,
                            Name = "Abu Tig"
                        },
                        new
                        {
                            Id = 1106,
                            GovernorateId = 11,
                            IsActive = true,
                            Name = "Sahel Selim"
                        },
                        new
                        {
                            Id = 1107,
                            GovernorateId = 11,
                            IsActive = true,
                            Name = "Al Ghanayem"
                        },
                        new
                        {
                            Id = 1108,
                            GovernorateId = 11,
                            IsActive = true,
                            Name = "Al Badari"
                        },
                        new
                        {
                            Id = 1201,
                            GovernorateId = 12,
                            IsActive = true,
                            Name = "Faiyum"
                        },
                        new
                        {
                            Id = 1202,
                            GovernorateId = 12,
                            IsActive = true,
                            Name = "Ibsheway"
                        },
                        new
                        {
                            Id = 1203,
                            GovernorateId = 12,
                            IsActive = true,
                            Name = "Senuris"
                        },
                        new
                        {
                            Id = 1204,
                            GovernorateId = 12,
                            IsActive = true,
                            Name = "Tamiya"
                        },
                        new
                        {
                            Id = 1205,
                            GovernorateId = 12,
                            IsActive = true,
                            Name = "Itsa"
                        },
                        new
                        {
                            Id = 1206,
                            GovernorateId = 12,
                            IsActive = true,
                            Name = "Yousef El Seddik"
                        },
                        new
                        {
                            Id = 1301,
                            GovernorateId = 13,
                            IsActive = true,
                            Name = "Tanta"
                        },
                        new
                        {
                            Id = 1302,
                            GovernorateId = 13,
                            IsActive = true,
                            Name = "El Mahalla El Kubra"
                        },
                        new
                        {
                            Id = 1303,
                            GovernorateId = 13,
                            IsActive = true,
                            Name = "Kafr El Zayat"
                        },
                        new
                        {
                            Id = 1304,
                            GovernorateId = 13,
                            IsActive = true,
                            Name = "Zefta"
                        },
                        new
                        {
                            Id = 1305,
                            GovernorateId = 13,
                            IsActive = true,
                            Name = "Samanoud"
                        },
                        new
                        {
                            Id = 1306,
                            GovernorateId = 13,
                            IsActive = true,
                            Name = "Qutour"
                        },
                        new
                        {
                            Id = 1307,
                            GovernorateId = 13,
                            IsActive = true,
                            Name = "Basyoun"
                        },
                        new
                        {
                            Id = 1308,
                            GovernorateId = 13,
                            IsActive = true,
                            Name = "El Santa"
                        },
                        new
                        {
                            Id = 1401,
                            GovernorateId = 14,
                            IsActive = true,
                            Name = "Shibin El Kom"
                        },
                        new
                        {
                            Id = 1402,
                            GovernorateId = 14,
                            IsActive = true,
                            Name = "Sadat City"
                        },
                        new
                        {
                            Id = 1403,
                            GovernorateId = 14,
                            IsActive = true,
                            Name = "Menouf"
                        },
                        new
                        {
                            Id = 1404,
                            GovernorateId = 14,
                            IsActive = true,
                            Name = "Ashmoun"
                        },
                        new
                        {
                            Id = 1405,
                            GovernorateId = 14,
                            IsActive = true,
                            Name = "Quesna"
                        },
                        new
                        {
                            Id = 1406,
                            GovernorateId = 14,
                            IsActive = true,
                            Name = "Tala"
                        },
                        new
                        {
                            Id = 1407,
                            GovernorateId = 14,
                            IsActive = true,
                            Name = "Berket El Sab"
                        },
                        new
                        {
                            Id = 1408,
                            GovernorateId = 14,
                            IsActive = true,
                            Name = "El Bagour"
                        },
                        new
                        {
                            Id = 1501,
                            GovernorateId = 15,
                            IsActive = true,
                            Name = "Beni Suef"
                        },
                        new
                        {
                            Id = 1502,
                            GovernorateId = 15,
                            IsActive = true,
                            Name = "Al Wasta"
                        },
                        new
                        {
                            Id = 1503,
                            GovernorateId = 15,
                            IsActive = true,
                            Name = "Nasser"
                        },
                        new
                        {
                            Id = 1504,
                            GovernorateId = 15,
                            IsActive = true,
                            Name = "Ihnasia"
                        },
                        new
                        {
                            Id = 1505,
                            GovernorateId = 15,
                            IsActive = true,
                            Name = "Biba"
                        },
                        new
                        {
                            Id = 1506,
                            GovernorateId = 15,
                            IsActive = true,
                            Name = "Al Fashn"
                        },
                        new
                        {
                            Id = 1507,
                            GovernorateId = 15,
                            IsActive = true,
                            Name = "Sumusta"
                        },
                        new
                        {
                            Id = 1601,
                            GovernorateId = 16,
                            IsActive = true,
                            Name = "Damietta"
                        },
                        new
                        {
                            Id = 1602,
                            GovernorateId = 16,
                            IsActive = true,
                            Name = "New Damietta"
                        },
                        new
                        {
                            Id = 1603,
                            GovernorateId = 16,
                            IsActive = true,
                            Name = "Faraskur"
                        },
                        new
                        {
                            Id = 1604,
                            GovernorateId = 16,
                            IsActive = true,
                            Name = "Kafr Saad"
                        },
                        new
                        {
                            Id = 1605,
                            GovernorateId = 16,
                            IsActive = true,
                            Name = "Zarqa"
                        },
                        new
                        {
                            Id = 1606,
                            GovernorateId = 16,
                            IsActive = true,
                            Name = "Ras El Bar"
                        },
                        new
                        {
                            Id = 1607,
                            GovernorateId = 16,
                            IsActive = true,
                            Name = "Kafr El Batikh"
                        },
                        new
                        {
                            Id = 1701,
                            GovernorateId = 17,
                            IsActive = true,
                            Name = "Port Said"
                        },
                        new
                        {
                            Id = 1702,
                            GovernorateId = 17,
                            IsActive = true,
                            Name = "Port Fouad"
                        },
                        new
                        {
                            Id = 1703,
                            GovernorateId = 17,
                            IsActive = true,
                            Name = "Al Dawahy"
                        },
                        new
                        {
                            Id = 1704,
                            GovernorateId = 17,
                            IsActive = true,
                            Name = "Al Zohour"
                        },
                        new
                        {
                            Id = 1705,
                            GovernorateId = 17,
                            IsActive = true,
                            Name = "Al Arab"
                        },
                        new
                        {
                            Id = 1706,
                            GovernorateId = 17,
                            IsActive = true,
                            Name = "Al Manakh"
                        },
                        new
                        {
                            Id = 1801,
                            GovernorateId = 18,
                            IsActive = true,
                            Name = "Ismailia"
                        },
                        new
                        {
                            Id = 1802,
                            GovernorateId = 18,
                            IsActive = true,
                            Name = "Fayed"
                        },
                        new
                        {
                            Id = 1803,
                            GovernorateId = 18,
                            IsActive = true,
                            Name = "Qantara Sharq"
                        },
                        new
                        {
                            Id = 1804,
                            GovernorateId = 18,
                            IsActive = true,
                            Name = "Qantara Gharb"
                        },
                        new
                        {
                            Id = 1805,
                            GovernorateId = 18,
                            IsActive = true,
                            Name = "Tal El Kebir"
                        },
                        new
                        {
                            Id = 1806,
                            GovernorateId = 18,
                            IsActive = true,
                            Name = "Abu Suwir"
                        },
                        new
                        {
                            Id = 1901,
                            GovernorateId = 19,
                            IsActive = true,
                            Name = "Suez"
                        },
                        new
                        {
                            Id = 1902,
                            GovernorateId = 19,
                            IsActive = true,
                            Name = "Ataqah"
                        },
                        new
                        {
                            Id = 1903,
                            GovernorateId = 19,
                            IsActive = true,
                            Name = "Arbaeen"
                        },
                        new
                        {
                            Id = 1904,
                            GovernorateId = 19,
                            IsActive = true,
                            Name = "Faisal"
                        },
                        new
                        {
                            Id = 1905,
                            GovernorateId = 19,
                            IsActive = true,
                            Name = "Ganayen"
                        },
                        new
                        {
                            Id = 2001,
                            GovernorateId = 20,
                            IsActive = true,
                            Name = "Aswan"
                        },
                        new
                        {
                            Id = 2002,
                            GovernorateId = 20,
                            IsActive = true,
                            Name = "Kom Ombo"
                        },
                        new
                        {
                            Id = 2003,
                            GovernorateId = 20,
                            IsActive = true,
                            Name = "Edfu"
                        },
                        new
                        {
                            Id = 2004,
                            GovernorateId = 20,
                            IsActive = true,
                            Name = "Daraw"
                        },
                        new
                        {
                            Id = 2005,
                            GovernorateId = 20,
                            IsActive = true,
                            Name = "Nasr El Nuba"
                        },
                        new
                        {
                            Id = 2006,
                            GovernorateId = 20,
                            IsActive = true,
                            Name = "Abu Simbel"
                        },
                        new
                        {
                            Id = 2007,
                            GovernorateId = 20,
                            IsActive = true,
                            Name = "Kalabsha"
                        },
                        new
                        {
                            Id = 2101,
                            GovernorateId = 21,
                            IsActive = true,
                            Name = "Luxor"
                        },
                        new
                        {
                            Id = 2102,
                            GovernorateId = 21,
                            IsActive = true,
                            Name = "Esna"
                        },
                        new
                        {
                            Id = 2103,
                            GovernorateId = 21,
                            IsActive = true,
                            Name = "Armant"
                        },
                        new
                        {
                            Id = 2104,
                            GovernorateId = 21,
                            IsActive = true,
                            Name = "Tod"
                        },
                        new
                        {
                            Id = 2105,
                            GovernorateId = 21,
                            IsActive = true,
                            Name = "Qurna"
                        },
                        new
                        {
                            Id = 2106,
                            GovernorateId = 21,
                            IsActive = true,
                            Name = "Bayadeyah"
                        },
                        new
                        {
                            Id = 2201,
                            GovernorateId = 22,
                            IsActive = true,
                            Name = "Hurghada"
                        },
                        new
                        {
                            Id = 2202,
                            GovernorateId = 22,
                            IsActive = true,
                            Name = "Safaga"
                        },
                        new
                        {
                            Id = 2203,
                            GovernorateId = 22,
                            IsActive = true,
                            Name = "El Qoseir"
                        },
                        new
                        {
                            Id = 2204,
                            GovernorateId = 22,
                            IsActive = true,
                            Name = "Marsa Alam"
                        },
                        new
                        {
                            Id = 2205,
                            GovernorateId = 22,
                            IsActive = true,
                            Name = "Ras Ghareb"
                        },
                        new
                        {
                            Id = 2206,
                            GovernorateId = 22,
                            IsActive = true,
                            Name = "Shalateen"
                        },
                        new
                        {
                            Id = 2301,
                            GovernorateId = 23,
                            IsActive = true,
                            Name = "Kharga"
                        },
                        new
                        {
                            Id = 2302,
                            GovernorateId = 23,
                            IsActive = true,
                            Name = "Dakhla"
                        },
                        new
                        {
                            Id = 2303,
                            GovernorateId = 23,
                            IsActive = true,
                            Name = "Farafra"
                        },
                        new
                        {
                            Id = 2304,
                            GovernorateId = 23,
                            IsActive = true,
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 2305,
                            GovernorateId = 23,
                            IsActive = true,
                            Name = "Balat"
                        },
                        new
                        {
                            Id = 2401,
                            GovernorateId = 24,
                            IsActive = true,
                            Name = "Marsa Matrouh"
                        },
                        new
                        {
                            Id = 2402,
                            GovernorateId = 24,
                            IsActive = true,
                            Name = "El Hammam"
                        },
                        new
                        {
                            Id = 2403,
                            GovernorateId = 24,
                            IsActive = true,
                            Name = "El Dabaa"
                        },
                        new
                        {
                            Id = 2404,
                            GovernorateId = 24,
                            IsActive = true,
                            Name = "Sidi Barrani"
                        },
                        new
                        {
                            Id = 2405,
                            GovernorateId = 24,
                            IsActive = true,
                            Name = "Siwa"
                        },
                        new
                        {
                            Id = 2406,
                            GovernorateId = 24,
                            IsActive = true,
                            Name = "El Negila"
                        },
                        new
                        {
                            Id = 2501,
                            GovernorateId = 25,
                            IsActive = true,
                            Name = "Arish"
                        },
                        new
                        {
                            Id = 2502,
                            GovernorateId = 25,
                            IsActive = true,
                            Name = "Sheikh Zuweid"
                        },
                        new
                        {
                            Id = 2503,
                            GovernorateId = 25,
                            IsActive = true,
                            Name = "Rafah"
                        },
                        new
                        {
                            Id = 2504,
                            GovernorateId = 25,
                            IsActive = true,
                            Name = "Bir al-Abd"
                        },
                        new
                        {
                            Id = 2505,
                            GovernorateId = 25,
                            IsActive = true,
                            Name = "Nakhl"
                        },
                        new
                        {
                            Id = 2506,
                            GovernorateId = 25,
                            IsActive = true,
                            Name = "Hasana"
                        },
                        new
                        {
                            Id = 2601,
                            GovernorateId = 26,
                            IsActive = true,
                            Name = "Sharm El Sheikh"
                        },
                        new
                        {
                            Id = 2602,
                            GovernorateId = 26,
                            IsActive = true,
                            Name = "Dahab"
                        },
                        new
                        {
                            Id = 2603,
                            GovernorateId = 26,
                            IsActive = true,
                            Name = "Tor Sinai"
                        },
                        new
                        {
                            Id = 2604,
                            GovernorateId = 26,
                            IsActive = true,
                            Name = "Nuweiba"
                        },
                        new
                        {
                            Id = 2605,
                            GovernorateId = 26,
                            IsActive = true,
                            Name = "Saint Catherine"
                        },
                        new
                        {
                            Id = 2606,
                            GovernorateId = 26,
                            IsActive = true,
                            Name = "Taba"
                        },
                        new
                        {
                            Id = 2701,
                            GovernorateId = 27,
                            IsActive = true,
                            Name = "Kafr El Sheikh"
                        },
                        new
                        {
                            Id = 2702,
                            GovernorateId = 27,
                            IsActive = true,
                            Name = "Desouk"
                        },
                        new
                        {
                            Id = 2703,
                            GovernorateId = 27,
                            IsActive = true,
                            Name = "Fuwwah"
                        },
                        new
                        {
                            Id = 2704,
                            GovernorateId = 27,
                            IsActive = true,
                            Name = "Qallin"
                        },
                        new
                        {
                            Id = 2705,
                            GovernorateId = 27,
                            IsActive = true,
                            Name = "Sidi Salem"
                        },
                        new
                        {
                            Id = 2706,
                            GovernorateId = 27,
                            IsActive = true,
                            Name = "Baltim"
                        },
                        new
                        {
                            Id = 2707,
                            GovernorateId = 27,
                            IsActive = true,
                            Name = "Hamoul"
                        },
                        new
                        {
                            Id = 2708,
                            GovernorateId = 27,
                            IsActive = true,
                            Name = "Mutubas"
                        });
                });

            modelBuilder.Entity("Registration.Domain.Entities.Governorate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Governorates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Cairo"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Giza"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Alexandria"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Qalyubia"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Sharqia"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Dakahlia"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Beheira"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Minya"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Qena"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "Sohag"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "Assiut"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "Faiyum"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "Gharbia"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Name = "Monufia"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Name = "Beni Suef"
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            Name = "Damietta"
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            Name = "Port Said"
                        },
                        new
                        {
                            Id = 18,
                            IsActive = true,
                            Name = "Ismailia"
                        },
                        new
                        {
                            Id = 19,
                            IsActive = true,
                            Name = "Suez"
                        },
                        new
                        {
                            Id = 20,
                            IsActive = true,
                            Name = "Aswan"
                        },
                        new
                        {
                            Id = 21,
                            IsActive = true,
                            Name = "Luxor"
                        },
                        new
                        {
                            Id = 22,
                            IsActive = true,
                            Name = "Red Sea"
                        },
                        new
                        {
                            Id = 23,
                            IsActive = true,
                            Name = "New Valley"
                        },
                        new
                        {
                            Id = 24,
                            IsActive = true,
                            Name = "Matrouh"
                        },
                        new
                        {
                            Id = 25,
                            IsActive = true,
                            Name = "North Sinai"
                        },
                        new
                        {
                            Id = 26,
                            IsActive = true,
                            Name = "South Sinai"
                        },
                        new
                        {
                            Id = 27,
                            IsActive = true,
                            Name = "Kafr El Sheikh"
                        });
                });

            modelBuilder.Entity("Registration.Domain.Entities.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Registrations", (string)null);
                });

            modelBuilder.Entity("Registration.Domain.Entities.Address", b =>
                {
                    b.HasOne("Registration.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Registration.Domain.Entities.Governorate", "Governorate")
                        .WithMany()
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Registration.Domain.Entities.Registration", null)
                        .WithMany("Addresses")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("Registration.Domain.Entities.City", b =>
                {
                    b.HasOne("Registration.Domain.Entities.Governorate", "Governorate")
                        .WithMany("Cities")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("Registration.Domain.Entities.Registration", b =>
                {
                    b.OwnsOne("Registration.Domain.ValueObjects.PersonName", "FirstName", b1 =>
                        {
                            b1.Property<int>("RegistrationId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("FirstName");

                            b1.HasKey("RegistrationId");

                            b1.ToTable("Registrations");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationId");
                        });

                    b.OwnsOne("Registration.Domain.ValueObjects.PersonName", "LastName", b1 =>
                        {
                            b1.Property<int>("RegistrationId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("LastName");

                            b1.HasKey("RegistrationId");

                            b1.ToTable("Registrations");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationId");
                        });

                    b.OwnsOne("Registration.Domain.ValueObjects.PersonName", "MiddleName", b1 =>
                        {
                            b1.Property<int>("RegistrationId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("MiddleName");

                            b1.HasKey("RegistrationId");

                            b1.ToTable("Registrations");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationId");
                        });

                    b.OwnsOne("Registration.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("RegistrationId")
                                .HasColumnType("int");

                            b1.Property<string>("NormalizedValue")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)")
                                .HasColumnName("NormalizedEmail");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)")
                                .HasColumnName("Email");

                            b1.HasKey("RegistrationId");

                            b1.HasIndex("NormalizedValue")
                                .IsUnique()
                                .HasDatabaseName("UX_Registrations_NormalizedEmail");

                            b1.ToTable("Registrations");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationId");
                        });

                    b.OwnsOne("Registration.Domain.ValueObjects.MobileNumber", "MobileNumber", b1 =>
                        {
                            b1.Property<int>("RegistrationId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("MobileNumber");

                            b1.HasKey("RegistrationId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("UX_Registrations_MobileNumber");

                            b1.ToTable("Registrations");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FirstName")
                        .IsRequired();

                    b.Navigation("LastName")
                        .IsRequired();

                    b.Navigation("MiddleName");

                    b.Navigation("MobileNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("Registration.Domain.Entities.Governorate", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Registration.Domain.Entities.Registration", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
